### ISSUE TITLE
Add a page with DEI links

### ISSUE THREAD

**Issue by fatala22** [uscms-diversity-equity-inclusion/uscms-diversity-equity-inclusion.github.io#32]
Create a page and link from pull down under "Resources"

Text -  CMS Diversity Office     Link to: https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSDiversityOffice

Text - Fermilab Diversity and Inclusion   Link to:  https://diversity.fnal.gov/

Text - [Diversity and Inclusion Programme Link to https://diversity-and-inclusion.web.cern.ch/

Text - NIH Diversity Calendar Link to https://www.edi.nih.gov/more/calendar

**Comment by GuillermoFidalgo** [comment]
Ok, remind me in the upcoming days. 
I think there should be a @bot that could do this.
